### ISSUE TITLE
sudo command would be nice to have

### ISSUE THREAD

**Issue by milahu** [landley/toybox#111]
```
$ cowsay hello toybox
 ______________ 
< hello toybox >
 -------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```
please consider adding the sudo command
so i can write
```
$ echo 0 9999999 | sudo tee /proc/sys/net/ipv4/ping_group_range
```
instead of
```
# echo 0 9999999 > /proc/sys/net/ipv4/ping_group_range
```
came here via
```
$ toybox ping google.de
ping: socket SOCK_DGRAM 1: Permission denied
Kernel bug workaround (as root):
echo 0 9999999 > /proc/sys/net/ipv4/ping_group_range
```
stupid question:
why does iputils/ping work without that workaround?

edit, really came here via
https://github.com/docopt/docopt.rs/issues/1

> @rickmoen
> 
> Hi, Andrew. If you are willing to consider an alternative, Rob Landley created for the toybox project the '0BSD' license (Zero-Clause BSD License) by removing a requirements clause from 2-clause BSD, and resulting in text running about ten lines. Moreover, it's already an OSI Certified licence, albeit OSI hasn't yet cleared up some lingering name confusion.
> 
> Several years on, my (referenced) damning legal critique of Unlicense on the license-review mailing list still looks to me, IMO, fully merited, but I absolutely applaud your wish to use a copyfree licence. Maybe 0BSD will be your cuppa. (copyfree.org lists it as 'Toybox License'. As I said, there's a lingering name issue being cleared up: Rob is working on getting everyone to standardise on 0BSD as the short name, and Zero-Clause BSD License as the full name.)
> 
> -- Rick Moen
> rick@linuxmafia.com

so ... thank you Rob Landley for creating the [0BSD license](https://landley.net/toybox/license.html) : ]

**Comment by rany0** [comment]
Hello,

I believe the reason is that toybox doesn't have `setuid` bit set or has no capabilities (`getcap`). Having one of these will solve this problem.

For more info, check the permissions of the `iputil-ping` and compare it to the toybox one. You will notice that toybox doesn't have `+s`. Another way is to use capabilities. 

On a system using `setuid` for ping:
```
# ls -l /bin/ping
-rwsr-xr-x 1 root root 72776 Oct  5 17:34 /usr/bin/ping
 ```

On a system using capabilities: 
```
# getcap /usr/bin/ping
/usr/bin/ping = cap_net_raw+ep
```
`cap_net_raw` is needed for sending ICMP packets.

**Comment by rany0** [comment]
`setuid` basically lets `/usr/bin/ping` run as the owner, which in this case, is `root`. 

A more secure approach is to use capabilities, because `ping` would not run as root. This is what most Linux distros do nowadays.

**Comment by landley** [comment]
Toybox has suid handling plumbing (CONFIG_TOYBOX_SUID), and individual commands are annotated with TOYFLAG_STAYROOT and TOYFLAG_NEEDROOT and such.

I haven't done sudo yet because I need to research what exactly it does to cleanse its environment. I've got some plumbing (such as reset_env() in env.c) but sudo.ws has LD_PRELOAD strangeness and weird tty-related signal handling and I don't want to miss an important mitigation, which means I may have to break down and read the source code of another implementation (something I try to avoid doing for license reasons).

But in this case, the security issues may override the licensing concerns especially since sudo.ws is BSD licensed. I'm pretty sure I _don't_ have to do 90% of their weird historical overgrowth, but when talking security tools I need to know what it _is_ and why it's there so I can eliminate it.

It's better NOT to have a sudo than have one that's exploitable.

P.S. Toybox ping doesn't run as root, it uses IPPROTO_ICMP in SOCK_DGRAM instead of SOCK_RAW.

**Comment by rany0** [comment]
Thanks for responding to this old issue, landley. 

However, as a beginner to Linux, I am wondering why you have chosen to use `SOCK_DGRAM` over `SOCK_RAW`. 

According to `man 7 icmp`:

```
       A user protocol may receive ICMP packets for all local sockets by opening a raw socket with the protocol IPPROTO_ICMP.  See raw(7) for more information.  The types of ICMP packets  passed  to
       the socket can be filtered using the ICMP_FILTER socket option.  ICMP packets are always processed by the kernel too, even when passed to a user socket.
```

So, the Linux manual recommends using `SOCK_RAW` and makes no mention of `SOCK_DGRAM`. In addition, using `SOCK_RAW` would mean that there would be no need for the "kernel bug workaround" because there would be no "permission denied" error.

**Comment by rany0** [comment]
I think I found the answer to "Why use `SOCK_DGRAM` over `SOCK_RAW`?".

Considering `toybox` has a focus on being portable, this note from the same man page might explain your decision:

```
       As many other implementations don't support IPPROTO_ICMP raw sockets, this feature should not be relied on in portable programs.
```

Also, using `SOCK_DGRAM` means that there would be no need for `SETUID` or capabilities which is awesome. I didn't know that `SOCK_DGRAM` doesn't need these things. 

My source for that is: https://lwn.net/Articles/443051/

**Comment by rany0** [comment]
While not needing `SETUID` or capabilities for ping function is fantastic, main disadvantage is that the default Linux option for `/proc/sys/net/ipv4/ping_group_range` is to not allow anyone to create ICMP sockets, which makes no sense. I don't get why they did that.

Adding
```
echo 0 9999999 > /proc/sys/net/ipv4/ping_group_range
```
to the startup script solves that, so it is kind of a minor problem.

**Comment by landley** [comment]
Because SOCK_RAW requires root and SOCK_DGRAM does not.

As for ping_group_range being stupid and pointless: yes, it is. I sent a patch to fix it, which lkml ignored. http://lkml.iu.edu/hypermail/linux/kernel/1710.3/04715.html

**Comment by MathGeniusJodie** [comment]
might be worth investigating doas https://en.wikipedia.org/wiki/Doas

**Comment by enh-google** [comment]
doas doesn't seem to solve any of the limitations of sudo that we've been sad about? from https://man.openbsd.org/doas it seems like you write the configuration to a file (which is usually _less_ convenient) and from https://man.openbsd.org/doas.conf.5 it seems like the configuration options don't actually cover any of the extra stuff that would be useful to have in a "super sudo".

given its OpenBSD source, i think doas is deliberately a more _limited_ option, rather than the more general tool that would be useful for [amongst other things] writing "interesting" tests.

**Comment by enh-google** [comment]
sudo is already mentioned in the status page as "not started yet" (but on the to-do list): https://landley.net/toybox/status.html
