### ISSUE TITLE
id command expects id to have names but that's optional

### ISSUE THREAD

**Issue by dlegaultbbry** [landley/toybox#117]
The id command expects all given uids, gids and sgids to exist in textual form but I don't think this is required at all by the specs and limits the usefulness of the command.

See http://pubs.opengroup.org/onlinepubs/009695399/utilities/id.html

"If any of the user ID, group ID, effective user ID, effective group ID, or supplementary/multiple group IDs cannot be mapped by the system into printable user or group names, the corresponding "(%s)" and name argument shall be omitted from the corresponding format string."

**Comment by enh** [comment]
Is there an easy way to reproduce this from the shell, or do I need to a C program that calls setgroups(2)?

**Comment by dlegaultbbry** [comment]
On QNX we have a utility that can do that easily and I found that you can have something similar to this tool in this repo 
http://git.skarnet.org/cgi-bin/cgit.cgi/s6/

http://www.skarnet.org/software/s6/s6-applyuidgid.html

**Comment by landley** [comment]
sudo has -u and -g options.

**Comment by landley** [comment]
Ah, but I see it won't let even root select nonexisting ones. (That's why I had a todo item to add -u UID and -g GID[,...] to su, which I haven't done yet because I need to figure out what the -s and -c backwards compatibility stuff looks like with the "add arbitrary arguments to the end of the command line". I think it means when you do -u or -g the first argument isn't treated as a username, and when you add arguments it doesn't do -s unless you specify -s or -c...)
