### ISSUE TITLE
Need update of binaries

### ISSUE THREAD

**Issue by HemanthJabalpuri** [landley/toybox#122]
Sir can you please update binaries to 0.8.0 in http://landley.net/toybox/bin/ .....
Thanks

**Comment by landley** [comment]
Oops. I uploaded the binaries to http://landley.net/toybox/downloads/binaries/0.8.0/ back when I did the release, but forgot to move the symlink. Fixed. Thanks for the heads up.

**Comment by HemanthJabalpuri** [comment]
> Oops. I uploaded the binaries to http://landley.net/toybox/downloads/binaries/0.8.0/ back when I did the release, but forgot to move the symlink. Fixed. Thanks for the heads up.

Thanks...
sir can we directly use the binaries in android or needs some patches like busybox?

**Comment by landley** [comment]
That's an Elliott question, but... sort of?

These binaries are statically linked against musl-libc (using a gcc+musl toolchain from https://github.com/richfelker/musl-cross-make via https://github.com/landley/mkroot). I also regression test the build against the Android NDK (an llvm-bionic toolchain similar to the one in AOSP).

Things like sed and grep should work fine. Things like "ps" require special selinux annotation on the host to be able to read the data they need to function (which the AOSP build provides but the other build environments don't, and which require root privilege to install). And anything to do with user accounts (which even "ls" tries to look up) has the problem that musl expects /etc/passwd to have useful info while bionic keeps this in a database (which in then requires selinux annotations to read)...

Toybox won't need any _patches_ (AOSP builds unmodified toybox, all their modifications are adding a seperate build script because they don't use make), but android in general requires a special build environment (its own libc plus xattrs to allow access via SELINUX; sort of a much more granular suid bit) to let toybox exercise its full range of capabilities in that system.

**Comment by enh** [comment]
Everything landley said, plus musl (or glibc) binaries try to use system calls that are prohibited on Android via seccomp/SELinux/being compiled out of the kernel. Only those system calls used by bionic are actually supported (to try to reduce the testing/validation costs, opportunity for security holes, differences between LP32 and LP64 code paths, and need to maintain compatibility for stuff we don't even use). Typical examples are where there's a newer -at variant of a system call. arm64 *only* has those system calls, so we moved arm over too to increase code coverage, and then blocked most of the non-"at" originals.

These failures should be pretty clear: your process will be [killed by the kernel for a seccomp violation](https://source.android.com/devices/tech/debug/native-crash#seccomp).

**Comment by richfelker** [comment]
This is frustrating and I don't know any good solution for it. Support for the old syscalls is necessary for binaries to be able to run on kernels that lack the new ones. We generally prefer to always use the oldest syscall that satisfies the need to implement a function, so as not to have to have multiple versions of the code with runtime fallback when one fails. Doing it the other way around would work, but increases code size and has a few other problems as well. One is that it relies on the newer syscall failing with ENOSYS if it's not supported, but my understanding is that some seccomp setups, including reportedly Docker's default one, cause ENOSYS to get suppressed and replaced with EPERM in some situations. If so, this would break the fallback sequence. I'm also worried that Android will continue to remove syscalls we need just because Bionic doesn't use them, in which case trying to solve the problem would be as futile and Kafkaesque as trying to be compatible with systemd.

**Comment by HemanthJabalpuri** [comment]
> Oops. I uploaded the binaries to http://landley.net/toybox/downloads/binaries/0.8.0/ back when I did the release, but forgot to move the symlink. Fixed. Thanks for the heads up.

Sir can you please add ability for file command to optionally use a magic file like in file -m

**Comment by landley** [comment]
Toybox has a design goal to work standalone (if it's the only binary in a chroot, it should function, although you may want to mount /proc and /sys). The current toybox "file" is basically an if/else staircase doing different checks in C.

That said, posix has a magic file format specified in the extended description of http://pubs.opengroup.org/onlinepubs/9699919799/utilities/file.html and I could add that. I note that this is _not_ the file format used by Ubuntu's /usr/share/file/magic.mgc (which is some binary thing full of NUL bytes):

$ file /usr/share/file/magic.mgc
/usr/share/file/magic.mgc: magic binary file for file(1) cmd (version 10) (little endian)

Given that it wouldn't be compatible with whatever Ubuntu's doing, would you still want it?

P.S. The project has a mailing list...
