### ISSUE TITLE
toysh status?

### ISSUE THREAD

**Issue by cesss** [landley/toybox#131]
How much work is still required to have `toysh` promoted out of the pending category? I'd like to use a minimalistic shell in my everyday work. I don't need the Bash-isms as discussed on [this issue](https://github.com/landley/toybox/issues/77), but however, there are some usability features I'd want to have:

- Support for UTF8-encoded pathnames and strings

- Tab auto-completion for commands in the PATH and for filenames.

- Command history attached to the up/down cursor keys.

I don't need any other extra feature: I'm fine with standard Bourne shell scripts (supposing `toysh` has such support complete).

Note: I'm not saying I'm against having Bash-isms into `toysh`. I think it would be indeed a bonus, because you would be able to run much more scripts. I'm just saying that for me that's not required, while the above items are.

**Comment by nykula** [comment]
A year optimistically. You'll be surprised but the standard Bourne shell is the tricky part, not bashisms. Subscribe to commits with the watch button and follow the mailing list, Rob sometimes writes down interesting syntactic weirdnesses as he wrestles them. The priority is to have AOSP able to build itself.

**Comment by landley** [comment]
I'm giving a "busybox vs toybox" talk on August 22 and I'm trying to get toysh promoted before then. It may not do everything I want, but should be basically usable.

**Comment by geoff-codes** [comment]
Have you thought about just pulling in (the necessary parts of) lksh (mksh)? It can (as far as I can tell) perfectly emulate everything from the Almquist shell to ksh93, dash, and (if you like) a very healthy helping of bashisms. Infinitely configurable, ISC licensed.

(Just make sure you get it from the CVS repo, the GitHub mirror is wonky).

**Comment by cesss** [comment]
> Have you thought about just pulling in (the necessary parts of) lksh (mksh)? It can (as far as I can tell) perfectly emulate everything from the Almquist shell to ksh93, dash, and (if you like) a very healthy helping of bashisms. Infinitely configurable, ISC licensed.
> 
> (Just make sure you get it from the CVS repo, the GitHub mirror is wonky).

Regarding pulling in parts of other shells, I think that would be against what `toybox` is. I mean, if you want to combine `toybox` with an existing shell, you can do that today, no need to pull-in the existing shell into `toybox`, just build them both side by side.

IMHO, it would make more sense to study the original Bourne sources (or the ones released through OpenSolaris, currently maintained in [schilytools](https://sourceforge.net/projects/schilytools/) by Jörg Schilling) and then do a new implementation from scratch that doesn't inherit obligations(*) from previous licenses (OpenSolaris is CDDL --weak copyleft, but not MIT).

(*)I'm no legal expert, so I'm not claiming what kind of reimplementations would inherit licenses and which ones wouldn't.

**Comment by landley** [comment]
Android _does_ build toybox and mksh side by side today.

Why write a new one when there are already multiple implementations of this code out there?

I can see how this could be a concern. When the "gnu project" was announced, the bell labs, berkeley, and coherent codebases already existed, and minix started at the same time and shipped first (linux started life on comp.os.minix and inherited its open source development community)

For one thing mksh is under a different license, toybox is 0BSD which is a public domain equivalent license, mksh is under a license that requires you to copy a specific blob of text into derivative works. (I asked the mksh author if he'd be willing to relicense and the answer was no, I forget why. Probably because he has third party contributors he'd have to track down like I did in 2011 when I relicensed.)

In addition, gluing together existing projects is the http://beastiebox.sourceforge.net/ approach, you're welcome to use that if you prefer. Toybox tries not to have repeated code, shared code should go in lib/ and commands should use it. An external project would have its own implementations of lots of stuff we have in lib/ and rewriting it to be a proper toybox command is actually more work than doing a new one.

Plus mksh doesn't do what I want it to. I'm trying to make a proper bash replacement, which means my "design" involves reading the bash man page, thinking how things might work, and then running tests against bash to see the result of undocumented corner cases. I already know places mksh differs from bash ("VAR=VALUE function" and "VAR=VALUE exe" differ in behavior, the first sets the variable persistently the second is only for the life of the exe)...

Here, I updated http://landley.net/toybox/design.html , does that answer your questions?

**Comment by landley** [comment]
The actual update was https://github.com/landley/toybox/commit/1c5cb5a2d8a21b913355b443f377154ac62bfecf by the way.

**Comment by geoff-codes** [comment]
Gotcha. Fair enough! 👍

**Comment by enh-google** [comment]
toysh still a work in progress. see rob's blog (https://landley.net/notes.html) or subscribe to the mailing list for regular progress updates.

**Comment by landley** [comment]
It's coming up on 5000 lines of source code (sigh) and I'm actually testing it against real world scripts now to find new bugs. Still a lot of known missing stuff and the big thing I haven't implemented yet is command line editing and history (because as soon as I do I'm gonna get a FLOOD of bug reports from people trying to use it), but I'm past the halfway point and probably past the 2/3 point? It does $((math)) and "for ((i=0; i<10; i++)); do echo $i; done" now and everything.

**Comment by enh-google** [comment]
(funnily enough, i was thinking about mksh vs toysh over my recent week off, and "command line editing that assumes at least vt100 and doesn't try to do everything with \b and \x20" was actually the biggest user-visible advantage i could think of based on the bugs i've had reported against mksh.)

**Comment by landley** [comment]
I have maybe 1/3 of it coded in a fork here, but the instant I check it in people will assume toysh is finished, and it doesn't run /usr/bin/ldd or the toybox test suite yet.

Toybox building under toysh and running its own test suite in mkroot is probably my threshold for promoting it. (And yes it needs command editing+history before promoting.)

MY big pet peeve about bash's command history, by the way, is that if the previous line didn't start at the left edge (because something printed without a newline) then if you cursor up and edit the resulting line, your edits go in the wrong place and the line you run isn't what was displayed on the screen. This fix to this involves the "probe current cursor position" escape sequence at the end of each interactive prompt, plus probably SIGWINCH handling. (Using the probe probably makes the \[ and \] sections of $PS1 into NOPs, by the way. I have notes on this somewhere...)
