### ISSUE TITLE
0.8.2+ Fails to build on mips

### ISSUE THREAD

**Issue by kraj** [landley/toybox#194]
I started to see this error on mips platform with (gcc10/glibc-2.31), 

```
lib/portability.c:404:21: error: 'SIGSTKFLT' undeclared here (not in a function); did you mean 'SIGSTKSZ'?
  404 | #define SIGNIFY(x) {SIG##x, #x}
      |                     ^~~
lib/portability.c:416:3: note: in expansion of macro 'SIGNIFY'
  416 |   SIGNIFY(STKFLT), SIGNIFY(POLL), SIGNIFY(PWR),
      |   ^~~~~~~

```

detailed log [here](https://errors.yoctoproject.org/Errors/Details/412848/)

**Comment by landley** [comment]
http://landley.net/toybox/downloads/binaries/0.8.3/toybox-mips
http://landley.net/toybox/downloads/binaries/0.8.3/toybox-mipsel
http://landley.net/toybox/downloads/binaries/0.8.3/toybox-mips64

**Comment by landley** [comment]
A) If mips has the wrong signal number, poke Rich.

B) I applied your patch, but shouldn't it be # ifdef SIGWHATSIS instead of special casing "if not glibc and mips"? (I mean portability.c is the right place for that kind of ugly... but that's ugly.)

(I had to put a space between the # and ifdef or else microsoft github had an undismissable pulldown menu popping up hidding the comment button. Bravo, microsoft github.)

**Comment by enh-google** [comment]
(for anyone missing the context, this is in reference to my comment on the pull request where i said "mips doesn't have SIGSTKFLT. i've no idea why musl claims it's signal 7. the kernel disagrees, calling that SIGEMT.")

> A) If mips has the wrong signal number, poke Rich.

for A i was hoping that the submitter actually knows/cares about mips. maybe there's a good reason for what musl does?

gah, now you've made me go and look...
```
commit 6315004f6102dca44c4ba50654a36967b8b9c2a6
Author: Rich Felker <dalias@aerifal.cx>
Date:   Wed Jul 11 04:22:13 2012 -0400

    initial version of mips (o32) port, based on work by Richard Pennington (rdp)
```

so, no. since i've wasted this much time already, i'll send them a mail...

> B) I applied your patch, but shouldn't it be # ifdef SIGWHATSIS

yes, that's what i was trying to say on the pull request --- glibc isn't the point here. a quick grep of the kernel suggests sparc and alpha also don't have SIGSTKFLT. (afaik no arch _uses_ it.)

> (I had to put a space between the # and ifdef or else microsoft github had an undismissable pulldown menu popping up hidding the comment button. Bravo, microsoft github.)

to be fair, github was doing that *long* before MS :-) (you can just keep typing though and it'll go away.)

**Comment by richfelker** [comment]
I'm not sure how this came to be, but indeed it looks wrong (on all 3 MIPS archs not just the "mips" one) and I'll fix it. Could you share a bit more about the mechanism of how this broke at compiletime so I'm aware in case it comes up in other programs and know how to identify this as likely what they're seeing?

**Comment by enh-google** [comment]
back when we had never-finished bits of mips support in Android, this was one of the more common build failures. to this day i think we have a few #ifdef SIGSTKFLTs lying around, even though they're no longer needed.

i think "compiles for mips on musl but doesn't compile with any other libc" is probably the test!

**Comment by richfelker** [comment]
Ah, I see - the original error report was building on glibc. Yes, the fix should just be `#ifdef SIGSTKFLT` (and also add a `#ifdef SIGEMT` case), not hard-coding assumptions about glibc or musl. This will be fixed in next musl release to define the correct signal name.

**Comment by landley** [comment]
What's the #ifdef SIGEMT for?

**Comment by enh-google** [comment]
at the moment we have SIGEMT in an `__APPLE__` ifdef. but it turns out there's a SIGEMT on mips linux too. so it should move out of the `__APPLE__` and just be `#ifdef SIGEMT` instead.

**Comment by landley** [comment]
Committed in 824663599378
