### ISSUE TITLE
getcwd(NULL, size) is a glibc-extension

### ISSUE THREAD

**Issue by E5ten** [landley/toybox#226]
I don't know if this is known, and accepted as a requirement on top of the standard for toybox, or not.
This issue is for either making sure the former is the case, or if not, an actual issue to be solved.
EDIT: specifically, the extension is having getcwd allocate sufficient memory to fit the working directory by giving NULL as the buffer argument.

**Comment by E5ten** [comment]
A solution could just be using a statically allocated `char buf[PATH_MAX]`, and erroring if that isn't sufficient because the directory shouldn't exceed PATH_MAX.

**Comment by enh-google** [comment]
it's not _just_ a glibc extension --- Android, BSD, iOS, macOS, ... is there anything that _doesn't_ support this?

or, as rob will doubtless say later "what problem are you trying to solve here?" :-)

**Comment by E5ten** [comment]
Sorry I didn't mean to imply that this wasn't supported outside of glibc, I was just using it to indicate that it's an extension that I was assuming originates from glibc, because extensions often seem to, and because the glibc man page says this
```
As an extension to the POSIX.1-2001 standard, glibc's getcwd() allocates the buffer dynamically
using malloc(3) if buf is NULL
```

**Comment by enh-google** [comment]
yes, but "what problem are you trying to solve here?". are you trying to build & run toybox on a system that _doesn't_ support this?

**Comment by landley** [comment]
The man page on this https://man7.org/linux/man-pages/man2/getcwd.2.html was last UPDATED to mention posix-2001 (19 years ago, I.E. SUSv2), and the current posix spec explicitly says "If buf is a null pointer, the behavior of getcwd() is unspecified" because they know everybody's implemented auto-allocation here for many years but they're too bureaucratically paralyzed to document reality.

If an actual failure happens (which should be a pretty obvious segfault on whatever system doesn't do it) we can move the existing xgetcwd() wrapper to portability.c (or poke whoever it is to fix their libc). But until then, I officially do not care. It _must_ auto-size these days because PATH_MAX is not a thing anymore and hasn't been for quite some time. (It's like /etc/mtab needing to be a symlink to /proc/self/mounts: I don't care if the "standard" has caught up yet, NOT doing it is stupid).
