### ISSUE TITLE
find -type list

### ISSUE THREAD

**Issue by kevinaj** [landley/toybox#227]
Toybox version 0.8.3
Android 11 (Stock emulator)

When using the `find` command's `-type` list only the first type in the list is honored.

Examples: 
1. `find / -path /proc -prune -o -type b,s` will return only block types
2. `find / -path /proc -prune -o -type s,b` will return only socket types

`find` on ubuntu 20.04 (version 4.7.0) will properly return both block and socket types for both example commands

Splitting the two types into separate flags works properly:
`find / -path /proc -prune -o type s -o -type b` will return both block and socket types

**Comment by enh-google** [comment]
the same example fails on the host too. patch sent to mailing list: http://lists.landley.net/pipermail/toybox-landley.net/2020-July/011899.html

**Comment by enh-google** [comment]
(in the patch i've been lenient and allowed any ',' anywhere, or not. findutils won't even allow a trailing ','. happy to send out a less lenient patch if @landley prefers.)

**Comment by landley** [comment]
Lenient's fine, but I did wince a bit at the "fixes #227" in the commit message rather than an explanation of the issue. (Policy of not replying on microsoft github to continue to exist.)

Applied, tweaked, and pushed. Why does it think I closed it? Is "fixes #227" github magic? In that case I DEFINITELY don't like it. Grrr.

**Comment by enh-google** [comment]
yes, it's magic, and that's why i used it. if you don't like it though, i'll stop. (especially since i can now close a fixed issue myself rather than needing to nag you, i don't even need "fixes" any more. i closed the file(1) GIF issue for you the other day, but let me know if you'd prefer to be nagged instead :-) )

**Comment by landley** [comment]
Feel free to tidy github's bugzilla without me. :)

I acknowledge github exists but I'm reluctant to preclude any workflow NOT using it. "This is #227" strikes me like one of those "b/" links to android internal bug servers that the rest of us can't access. I almost edited your patch to change it to https://github.com/landley/toybox/issues/227 but didn't because A) that's putting words in another dev's mouth, B) if microsoft github someday goes the way of hotmail/vine/livejournal/geocities/sourceforge/aol/myspace/google+/del.ici.ous... would that URL still work?

I admit I'm weird: I have local backups of my talk videos because http://landley.net/hg/kdocs/rev/4e510536c3c8#l1.54 and https://www.spinics.net/lists/linux-embedded/msg04243.html and now endless midroll ads as policy literally intended to "annoy" users, and that's what I _expect_ online services to do. It's just a question of when.

**Comment by enh-google** [comment]
> Feel free to tidy github's bugzilla without me. :)

done. merged/obsolete pull requests too. i've tried to include the relevant SHAs for things that were fixed and wording along the lines of "discussed on the mailing list" for stuff you rejected.

>  "This is #227" strikes me like one of those "b/" links to android internal bug servers that the rest of us can't access.

true. my thinking was "if github's gone it doesn't matter", but at least including the URL would have explained what #227 had once meant. i don't actually know whether github also recognizes those, but judging by the way it mangled what i assume was your attempt to explicitly give the URL in the previous comment, i'd bet it treats them the same.

> sourceforge

unlike the others you mention, sourceforge _is_ still there, even though none of us are using it any more :-)

anyway, i'll try not to use #XXX in future!
