### ISSUE TITLE
--version and --help should mention who to get in touch with / report bugs

### ISSUE THREAD

**Issue by jidanni** [landley/toybox#231]
With coreutils, (find, etc.) --version and --help make very sure to mention who to get in touch with / report bugs.
Alas with toybox, it is quite a challenge to eventually find this GitHub issue page.

**Comment by enh-google** [comment]
yeah, that's basically what #50 asks for.

**Comment by landley** [comment]
Google "android toybox", first hit is http://landley.net/toybox/about.html and if you can't figure out the source control, mailing list, or irc links at the left you can go to the top level landley.net page which says who I am and has a link to my personal email at the end of the navigation bar on the left. (Judging by the volume of email I get, people figure this out.) If you google "toybox" without android, we're not the first hit but the wikipedia page for the project is still on the first page of hits, and that gives my name as maintainer (so you can google me) and links to the toybox web page (the news/release notes page rather than the about page, but same nav bar) and this github.

I can make my name and contact info more prominent, but I like to think the project isn't just me? (Over 100 other people have contributed to the project, and if it's an Android thing you want Elliott anyway.)

**Comment by jidanni** [comment]
Yes, without a concrete URL, we all have to Google to eventually find this spot to report bugs at.

One guesses that is purposely the way of filtering out the "people who are looking for a help group"... "got to be smart to know how to contact us."

Anyway yes, but
- What if Google goes down?
- What if the new Toybox car from Toyota wipes you out of search results for ever. Then it is too late.

**Comment by landley** [comment]
Without a URL you can google to find it, yes.

You've actually found a suboptimal spot, I personally prefer posts to the toybox mailing list, and failing that personal email. But you found option number three, and option number 4 is usually some sort of google/AOSP channel ala https://source.android.com/setup/contribute/report-bugs and then 5 woulud be one of the vendors like lineageos that forwards it on to me, and so on down. *shrug* They all work, it's a wide net.

It's not _intentionally_ a way of filtering for intelligence, no.

"yes but..." Did you seriously just ask what if there stops being ANY way to search the internet? (How has the linux kernel survived all this time not mentioning https://kernel.org in the kernel startup messages, a website that predates google, so had to use yahoo.com to find it back in the 90's.)

I'm sure the toyota car would be welcome on the https://en.wikipedia.org/wiki/Toy_box page with all the  other ones, and that doesn't even include the "disney infinity toybox" app on Android (https://www.youtube.com/watch?v=vOi2puWPFqE) which used to be the main other "android toybox" search hit, although there's a bunch of other random https://play.google.com/store/apps/details?id=com.toybox&hl=en_US results. This is not new. (I started toybox in 2006, coming up on 14 years ago.)

"the biggest companies..." I'm not a company. I'm a hobbyist open source developer. Toybox was something like 8 years old when Google started using it (https://lwn.net/Articles/629362/), and since then Google has given me a pair of $200 gift cards (one of which I actually activated and the other I lost), and a nice throw blanket with the Google logo on it (it's very fluffy, the dog loves it). And Elliott bought me lunch once when I visited his hometown for an embedded linux conference.

That said, I did add a URL to toybox --help yesterday (because I took Elliott referring to the 4 year old request as an implied endorsement, not because 2 people in 4 years had trouble googling).

**Comment by jidanni** [comment]
(https://source.androi... wonder how many bugs never made it out of there to finally get here where they belonged...)

**Comment by landley** [comment]
Android has a full time paid development staff, and the android base OS maintainer is the second most active contributor on the toybox project, so I'm guessing "none"?

As for "belong", they don't get forwarded here to github, they go to http://lists.landley.net/pipermail/toybox-landley.net/2020-July/011904.html resulting in http://lists.landley.net/pipermail/toybox-landley.net/2020-August/011907.html and then show up in the git log ala https://github.com/landley/toybox/commit/9552ab89c617 without ever being "issues" here.

I'm all for improving the project's visibility and making it easier for users and developers. I've tried to get the word out in writeup and youtube videos and so on. But https://www.goodreads.com/quotes/477087-remember-when-people-tell-you-something-s-wrong-or-doesn-t-work remains true, and another common problem to thinking one's personal preferences are universal. (The "what I want is by definition what's best for everyone" fallacy probably has a pithy name but I'm not thinking of it.)

"Here is a problem." Acknowledged. "You must do this, I command you, volunteer who I treat as paid help." Tends to get some pushback.

There's a century of literature on volunteer-run projects that predates the invention of the computer, from science fiction conventions to fire departments to https://www.fastcompany.com/1100800/why-volunteers-dont-come-back and so on, but open source has its own fairly large body of literature at this point. My 2010 talk on this was called "the prototype and the fan club" and years before that I was mentioned in https://firstmonday.org/ojs/index.php/fm/article/download/1105/1025, but the best _conceptual_ introduction to the topic is probably the three excellent Clay Shirky videos I linked from https://www.kernel.org/doc/ (They're not at the top. You have to search for "Shirky" in the page.)

**Comment by enh-google** [comment]
> That said, I did add a URL to toybox --help yesterday (because I took Elliott referring to the 4 year old request as an implied endorsement, not because 2 people in 4 years had trouble googling).

actually, i just wanted to get an executive decision from you on that long-lingering bug. fwiw, i preferred the old --help output --- i'm a sucker for anything i can copy & paste into a terminal :-)

but i don't think it matters much either way. i don't think either "folks who can't find the instructions to install toybox" or "folks who can't find toybox on the web at all" are large groups.
