### ISSUE TITLE
Adding prefix to toybox produces error

### ISSUE THREAD

**Issue by MuntashirAkon** [landley/toybox#238]
Adding prefix to toybox (e.g. renaming toybox to mytoybox) produces the following error:

> toybox: Unknown command ./mytoybox (see "toybox --help")

Is there anyway around to this problem?

**Comment by landley** [comment]
Yes, use a suffix instead of a prefix as described in the README.

https://github.com/landley/toybox/blob/master/README#L68

**Comment by MuntashirAkon** [comment]
Yes, I've read that. I was wondering if there was a way to add a prefix to it anyway.

**Comment by landley** [comment]
Well, _sort_ of? There's 3 mechanisms here, and maybe you want the third one:

First, command multiplexers figure out what to do based on what name they're called with. You can call the toybox binary "banana" if you want, and as long as the symlinks that point to it are "ls" and "cat" and such it should work because it never looks at the binary's filename if it recognizes the symlink's filename. 

Second, the toy_find() function that recognizes names explicitly checks for toybox as a prefix when looking up what command to run:

https://github.com/landley/toybox/blob/master/main.c#L32

Third, if the lookup fails the toybox_main() function (which implements the "toybox" command but is also called directly from main() for the multiple command case) will dereference one layer of symlink and try again, so if the name it doesn't recognize is a symlink that points to a name it DOES recognize, toybox will do that:

https://github.com/landley/toybox/blob/master/main.c#L185

This allows you to rename toybox commands by symlinking to a symlink. So if you really NEED something called "gsed" you can "ln -s $(which sed) gsed" and it's supposed to work, even though toybox doesn't know what "gsed" is (and even though sed is itself a symlink to another filename).

So you could have a file "toybox-potato" somewhere and "ln -s toybox-potato potato-toybox" and then you could run potato-toybox using that symlink. (The prefix version it doesn't recognize is a symlink to a suffix version it _does_ recognize.) Note that it only checks ONE level of symlink, so the name of the file the symlink points to has to be something toy_find() can recognize. But the OS resolves multiple levels of symlinks, so you can create a symlink to a symlink to the actual file if you need to...

Does that provide what you're looking for? It would let you "potato-toybox ls -l".

**Comment by MuntashirAkon** [comment]
Thank you for the detailed reply. I think I've got my answer. I've to admit, this is really a clever implementation.

**Comment by MuntashirAkon** [comment]
> Second, the toy_find() function that recognizes names explicitly checks for toybox as a prefix when looking up what command to run. (This is the method you did NOT want to use, above.)

It appears that Android doesn't copy native libraries to /data/app/<package>-<id>/lib/<arch> if it doesn't have the `lib` prefix (adding `android:extractNativeLibs="true"` fixes that issue but not for all devices). I can't use /data/data/<package> directory as well since it's not supported in Android Q (and later). The only way, as recommended in an issue (in the Google issue tracker) is to utilise the native lib directory (or by copying it to the /data/local/tmp directory). But this doesn't work for devices without root or ADB, and apparently, some vendors forget to provide the `cp` command itself. So, it seems there's no choice but to use this second method (which you noted as _out of order_) or switch to busybox. What's your resolution on this? Is it safe to _edit_ that particular line to add `lib` as a prefix?

**Comment by landley** [comment]
If you want to deploy busybox, feel free. I'm not stopping you.

**Comment by MuntashirAkon** [comment]
> If you want to deploy busybox, feel free. I'm not stopping you.

Well, I find toybox a very interesting project. I just wish I could use it in my project. I've actually deployed a release already but Android has made things too much complicated to handle all the situation.

**Comment by landley** [comment]
If you have a solution that works for you already, go for it. I don't understand how since I implemented the same suffix design in busybox that I did in toybox, and I just tested the current busybox build and it doesn't understand prefixes either. But I take your word for it that switching from the project I currently maintain to the project I _used_ to maintain will fix your issue.

Good luck with it,

Rob

**Comment by MuntashirAkon** [comment]
> I just tested the current busybox build and it doesn't understand prefixes either.

Yes, I've tested it just now and it appears that it has the same problem. I've actually got the impression that it would work as libsu uses libbusybox.so in one of its modules. But later I've looked at the source code and found that it copies the binary as `busybox` in the `/data/data/<package-name>` directory. Can't you just fix the prefix issue though? Where exactly is the problem? I don't need all the toybox tools just the standard linux commands along with tar and its dependencies such as gunzip.

**Comment by MuntashirAkon** [comment]
> First, command multiplexers figure out what to do based on what name they're called with. You can call the toybox binary "banana" if you want, and as long as the symlinks that point to it are "ls" and "cat" and such it should work because it never looks at the binary's filename if it recognizes the symlink's filename.

So, if we are to extract, say `libtoybox.so` in the lib directory and create a symbolic link of it in some directory as `toybox` (without or without some suffix), it should work, right?

**Comment by landley** [comment]
You said you were going to switch to busybox. Ask them.
