### ISSUE TITLE
agetty(1) in Roadmap, but not in Status ?

### ISSUE THREAD

**Issue by subnut** [landley/toybox#261]
See, `agetty` is said to be in the roadmap -
https://github.com/landley/toybox/blob/76d3160cfabe15568f006ad530c105b9ad6fdcdd/www/roadmap.html#L1060
but it's nowhere to be seen in Status -
http://landley.net/toybox/status.html

So... agetty is coming or not? Any ETA?

**Comment by E5ten** [comment]
`getty` is mentioned in status, I assume that agetty will just be an alias to it.

**Comment by landley** [comment]
https://github.com/landley/toybox/blob/master/toys/pending/getty.c

https://unix.stackexchange.com/questions/255385/what-is-the-difference-between-getty-and-agetty

And as for status, I need to finish toysh before cleaning up more stuff in pending, but the one in pending works for other people? I'm not promoting it with those #defines and its own speed_mapper table duplicating the one in lib/tty.c and those #ifdefs in .c files instead of .h files and both print_prompt() and sense_baud can be inlined at their one and only callsite and STDIN_FILENO has been a constant 0 for 50 years and... Ahem. Cleanups.

**Comment by enh-google** [comment]
(i've sent a patch for as much of that as i could get done during breakfast
to the mailing list...)

**Comment by enh-google** [comment]
> And as for status

i _think_ what they meant was "why is agetty mentioned in <http://landley.net/toybox/roadmap.html> but not in <http://landley.net/toybox/status.html>?"

to which i think the answer is that "agetty is in a list of _packages_ in the roadmap, but getty is the _command_ that will be implemented, and which _is_ already on the status page".
