### ISSUE TITLE
`toybox [` not allowed

### ISSUE THREAD

**Issue by enh-google** [landley/toybox#265]
i can't remember whether this has come up before, but filing for posterity...

Debian has /bin/[ as well as /bin/test, but the toybox multiplexer doesn't accept `[`, just `test`. busybox seems to?

(this came up in the context of https://android-review.googlesource.com/c/platform/system/core/+/1563455/2..4/fs_mgr/tests/adb-remount-test.sh#b1659.)

**Comment by landley** [comment]
It used to be standalone and I can add it back if there's need. Just replace TOYFLAG_NOFORK|TOYFLAG_NOHELP with TOYFLAG_BIN|TOYFLAG_MAYFORK|TOYFLAG_NOHELP.

But the real problem is it switched from USE_TEST() to USE_SH() as the enable guard so it's always available when the shell is enabled. I made it a shell internal at the same time because otherwise "make sh" got confused by CONFIG_TEST also being enabled, but I may have already fixed that part...? If you make the above change and enable CONFIG_SH then you do get a [ symlink... but you have to enable the shell.

**Comment by landley** [comment]
Commit a577b476e45f

**Comment by enh-google** [comment]
wow, thanks, i assumed this would have to wait until after sh!

https://android-review.googlesource.com/c/platform/external/toybox/+/1573000 pulls in your changes and https://android-review.googlesource.com/c/platform/external/toybox/+/1573063 adds the symlink, so `adb shell [` should work in Android S, for anyone reading this years later. (which reminds me i should update the "what's in Android's toybox?" docs at https://android.googlesource.com/platform/system/core/+/master/shell_and_utilities/ now...)
