### ISSUE TITLE
hwclock not set clock with more 2069 year

### ISSUE THREAD

**Issue by ionutnechita** [landley/toybox#266]
Hi Rob Landley,

Observe this issue with toybox - hwclock.

\~ date -s "Jan 10 15:42:59 UTC 2070"; hwclock -w; hwclock -s; date; hwclock
**Fri Jan 10 15:42:59 UTC 2070
hwclock: ioctl 4024700a: Invalid argument
Sun Jan 20 15:43:21 UTC 2069
Sun Jan 20 15:43:21 2069  0.000000 seconds
/home # hwclock --version
toybox 0.8.1**

\~ date -s "Jan 10 15:42:59 UTC 2069"; hwclock -w; hwclock -s; date; hwclock
Thu Jan 10 15:42:59 UTC 2069
Thu Jan 10 15:42:59 UTC 2069
Thu Jan 10 15:42:59 2069  0.000000 seconds

QEMU x86_64 Target:
uname -a
Linux (none) 5.10.12 #1 Sun Jan 31 19:05:35 EET 2021 x86_64
Ubuntu Host:
Ubuntu 20.04.1 LTS
qemu-system-x86_64 --version
QEMU emulator version 4.2.1 (Debian 1:4.2-3ubuntu6.11)
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers

**Comment by landley** [comment]
Note the "ioctl: invalid argument"? We're passing a bigger time into the kernel and the kernel is saying it can't handle it. (Possibly because the underlying hardware clock on your board can't?)

As far as I can tell we did the right thing, the kernel is what complained. And in this case the data structures and parsing functions are all straight out of libc: for -w we do gettimeofday() and localtime_r() and then call an ioctl(). There aren't even lib/ wrappers to look at to confirm they're not messing with anything.

Rob

**Comment by ionutnechita** [comment]
This Kernel or Qemu cause this issue?

**Comment by enh-google** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1224023#c2 says:
```
You can't set hwtime >= 2070, this is a known system limit (1970 +100)

Linux drivers/char/rtc.c
                /* These limits and adjustments are independent of
                 * whether the chip is in binary mode or not.
                 */
                if (yrs > 169) {
                        spin_unlock_irq(&rtc_lock);
                        return -EINVAL;
                }
```
that code seems to be in drivers/rtc/rtc-mc146818-lib.c now, but seems relevant.

(fwiw, on mobile devices i've seen even earlier limits. afaik any tests we have that mess around like this don't test past 2040.)

**Comment by ionutnechita** [comment]
Understood, limitation is in Kernel space.
