### ISSUE TITLE
-Werror=missing-prototypes

### ISSUE THREAD

**Issue by coderofsalvation** [landley/toybox#267]
Hi, 

Thx for creating/maintaining toybox.
I was wondering what this error means, and how to fix it:

```
$ make menuconfig # I think i didn't (de)select anything here, just looked around a bit
$ make
...
main.c: At top level:
main.c:149:6: error: no previous prototype for 'toy_exec_which' [-Werror=missing-prototypes]
 void toy_exec_which(struct toy_list *which, char *argv[])
      ^~~~~~~~~~~~~~
$ uname -a                                      
Linux LENOVSQZ 4.4.0-18362-Microsoft #1049-Microsoft Thu Aug 14 12:01:00 PST 2020 x86_64 GNU/Linux
$ cat /etc/issue
Welcome to Alpine Linux 3.10
Kernel \r on an \m (\l)
```

> PS. this is run on Alpine ON windows 10 (WSL 1.0).

**Comment by landley** [comment]
It means your CFLAGS adds a compiler flag to error on things toybox has been doing all along which aren't an error? Toybox doesn't prototype local functions that are declared before their user.

**Comment by landley** [comment]
I added some more "static" annotations to local functions, but -Wbreak-everything still complains that there's no prototypes for gzip_main() and chown_main() even though they're no obviously different from every other command's main function? No idea what gcc is doing here. (Might be a side effect of inlining?)

**Comment by E5ten** [comment]
used V=1 with my make command to find the compiler command to run, and switched -c for -E to see what the preprocessed source of a file that has that warning with a _main function to see what it looked like (I used chgrp.c). I see this set of lines among the many decls of *_main functions:
```c
void chgrp_main(void);
void chmod_main(void);
void chgrp_main(void);
```
Based on that I'm guessing that the second chgrp_main should be chown_main, and something's going wrong with that? No idea what at this point though.

**Comment by E5ten** [comment]
I'm not entirely certain how the NEWTOY/OLDTOY stuff works, but I think for chown_main the cause is that the line for chown is:
```c
USE_CHOWN(OLDTOY(chown, chgrp, TOYFLAG_BIN))
```
and I think the `chgrp` there is supposed to mean that chown will use `chgrp_main`, as opposed to have its own `chown_main`, which is why it's not declared?

**Comment by E5ten** [comment]
Aside from chown, I don't see the warning for gzip_main, so I can't comment on that one. Other than that, I see this for a couple of commands in pending when I enable all of those (well, there are a ton of these warnings there, but almost all of them are just non *_main functions that are missing static). I see it for jobs_main in sh.c (which I think is just because jobs doesn't have a `USE_SH` line like the other shell builtins in sh.c. I also see the warning for openvt_main, but I'm unclear on why a declaration isn't present for that one.

**Comment by landley** [comment]
When a file legitimately has two command_main() but one of them is disabled, it's not an error for that other entry point not to be static: I'm explicitly relying on dead code elimination (with the -ffunction-sections -fdata-sections -Wl,--gc-sections) to optimize it out.

This compiler option is silly and I'm not really trying to support it, I was just using the excuse to add some static to things that aren't used outside their file to save the ELF table entry and maybe shave a few bytes off the resulting binary. (Dunno if it did because there's debug exports and such I'm largely ignoring. I haven't micromanaged "strip" in long enough I'd have to look up some of the details again...)

**Comment by E5ten** [comment]
I'm not talking about changing any of them to static, or doing anything about the openvt one at all, I was just noting what I was observing as the cause of the warning for that one. I was assuming that deleting chown_main was fine because it uses chgrp_main, but I guess I don't know if that would work if chgrp was disabled and chown was enabled.

**Comment by E5ten** [comment]
Ah disregard the second part, I didn't notice the commit related to that.

**Comment by enh-google** [comment]
reading "This compiler option is silly and I'm not really trying to support it" as "will not fix"...
