### ISSUE TITLE
GCC-11 format-security warning on sh toy

### ISSUE THREAD

**Issue by frikiluser** [landley/toybox#299]
Hi,

Using gcc-11.2 (from Debian Sid) I've found this warning.

```
toys/pending/sh.c:791:7: error: format not a string literal and no format arguments [-Werror=format-security]
  791 |       len += snprintf(ss+len, ss ? INT_MAX : 0, s);
      |       ^~~
```

CFLAGS used: `-g -O2 -ffile-prefix-map=/build/toybox-0.8.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wl,-z,now`

**Comment by enh-google** [comment]
(these get fixed when Android syncs with upstream, since we build with `-Werror=format-security` and `-Werror=unused-result`. in particular, i think everything mentioned here is already fixed.)

**Comment by landley** [comment]
I updated my llwrap script to build with those 2 flags but commit 6cf4d6d4d189 broke building defconfig under the Android NDK because passwd.c tries to use getspnam() which is no longer compile time probed for but has no prototype in bionic. I need to fix it before the release, but am trying to close other tabs first...
