### ISSUE TITLE
Low hanging fruit?

### ISSUE THREAD

**Issue by gregschmit** [landley/toybox#309]
Hi, I have become really interested in this project and I'd like to contribute, but it's been awhile since I wrote meaningful C code (mostly do python and ruby stuff these days). Are there any low-hanging fruit things that I could try to tackle? I noticed that some interesting commands that are documented as "pending" (like `adduser`, `addgroup`, `cd`) and I'm wondering if there are some easy things I could do to get those out of pending, like if they are just awaiting tests?

**Comment by landley** [comment]
Unfortunately if there was low hanging fruit I know about, I'd probably have done it by now, but additional eyeballs in toys/pending are always welcome. My last serious attempt at categorizing my todo list was probably http://lists.landley.net/pipermail/toybox-landley.net/2020-May/011752.html

Testing is nice to but it's not so much coming up with test files as reproducing specific issues. For example, the ongoing issues/308 thread is about a lack of testing in "cp" (or more accurately a lack of me understanding how selinux works and not having a test environment for a corner case, I just implemented something that probably won't cover a specific case, but can't be sure because I don't have any idea how to set selinux up that way). Meanwhile, issues/307 is about a btrfs issue I've tried and failed to reproduce under mkroot.

Speaking of mkroot, that http://lists.landley.net/pipermail/toybox-landley.net/2021-December/012756.html explanation I did (building upon https://landley.net/toybox/faq.html#mkroot) is part of a larger goal: I'm trying to work towards setting up a proper root test environment inside mkroot, for things that can only be tested as root or which require a known environment (such as having the kernel "dummy" network driver available). If I can run the existing toybox tests under mkroot, then I can start adding proper ifconfig tests and nontrivial ps tests and so on...

**Comment by gregschmit** [comment]
Ok, thanks I will check out some of the issues and see if I can make myself useful.

**Comment by enh-google** [comment]
one thing i always recommend is "try to switch to toybox for your daily work environment/weekend play environment, and find out what's not working for you". whether it be missing features or bugs or performance issues, it's a good way to ensure you're motivated to fix stuff, and even when you _don't_ find issues, you're still helping out by testing :-)
