### ISSUE TITLE
xparsedate can't parse nanoseconds

### ISSUE THREAD

**Issue by victorhsieh** [landley/toybox#319]
It seems xparsedate intends to support parsing a timestamp with nanosecond / 9-digit precision, but it actually doesn't work.
```
$ find -newerct @123.123456789
find: bad date @123.123456789
```

**Comment by victorhsieh** [comment]
Thanks for the quick fix again!

**Comment by paulwratt** [comment]
is anyone interested in passing a fix along to BusyBox? (even if its not a patch)

**Comment by landley** [comment]
Busybox and toybox are completely different codebases. (I started over from scratch when I left. I ported a few of the commands I'd written and thus owned the copyright for, and submitted a couple of toybox commands to busybox over the years, but there was signifcant porting work each way, and for stuff like sed and mount I just started over from scratch even though I wrote most of busybox's version.)

I check the busybox list every few weeks to see if they have interesting bug reports or feature requests that might apply to toybox as well, but I don't read their code without a good excuse (because license). Recently got embarassed by that, actually: http://lists.busybox.net/pipermail/busybox/2022-February/089462.html

**Comment by paulwratt** [comment]
(I only posted becuase BusyBox does not handle "nanoseconds", and only if someone was interested - I am not)

> Busybox and toybox are completely different codebases.

Yep, I knew that, hence "even if its not a patch"

> Recently got embarassed by that

;) Oh the joys of Life ..
