### ISSUE TITLE
xrunread stdin name conflicts

### ISSUE THREAD

**Issue by dlegaultbbry** [landley/toybox#371]
On QNX, stdin is a global header symbol so using that as a variable name doesn't quite compile.

Maybe rename it "in" or something else that is less prone to conflict in the namespace?

**Comment by landley** [comment]
You didn't say where, and you can have a local variable with the same name as a global variable?

**Comment by landley** [comment]
According to posix (https://pubs.opengroup.org/onlinepubs/9699919799/) stdin is extern FILE * stdin; and you can have a local variable with the same name as a global variable?

**Comment by dlegaultbbry** [comment]
QNX defines it in another way and it's a macro. It's no big deal to handle it internally.

**Comment by enh-google** [comment]
yeah, POSIX allows a macro and glibc and Android have effectively `#define stdin stdin`, but BSDs have something like `#define stdin __sF[0]` which i'd expect would break here? hmm... current macOS seems to have `#define stdin   __stdinp` so i guess they'd get away with it. maybe the other BSDs switched too (since we haven't heard complaints from the BSD guy)?

**Comment by enh-google** [comment]
> Is this the reason strcpy errors out?

no. file a new bug (but make sure to include: 1. what i did. 2. what i expected. 3. what i actually saw).

**Comment by landley** [comment]
I committed 3dae8ebfe590 a while back to try not to stomp on QNX's stdin, but I can't actually test if that fixed it?

**Comment by dlegaultbbry** [comment]
It's fine, I personally changed it to 'in' internally.
