### ISSUE TITLE
httpd dos problem

### ISSUE THREAD

**Issue by ShiKangBao** [landley/toybox#387]
normal
if I send it
```
GET 1.txt
```
![image](https://user-images.githubusercontent.com/34313868/195297122-045801a3-1633-4db2-a427-9bde673cc308.png)
```
HTTP/1.1 400 Bad Request
Server: toybox httpd/0.8.8
Date: Wed, 12 Oct 2022 08:51:41 GMT
Connection: close
```
but if I send it
POC
```
GET /forum.php HTTP/1.1
```
![image](https://user-images.githubusercontent.com/34313868/195297500-75336ab1-9004-44a1-acfc-74b433bafad1.png)
It must accept a carriage return before returning a response.
![image](https://user-images.githubusercontent.com/34313868/195297949-35f595f1-194f-4230-89db-292cc482c1e4.png)

Now let's observe the process.
If I send `GET 1.txt`,there are no related processes here.
![image](https://user-images.githubusercontent.com/34313868/195298652-9a8741d0-0ef3-4ed5-b95a-1ae63991f8f9.png)

If I send twice poc,there are two httpd in system.
![image](https://user-images.githubusercontent.com/34313868/195298891-5623521d-b14c-4f1b-8949-f6e4b20b1970.png)
httpd wait for my enter.

So, Let's look at network packets.

![image](https://user-images.githubusercontent.com/34313868/195299314-7b67abd4-3e5e-414e-87b4-e3bcb1335f74.png)

If attacker send many network packages to toybox httpd service, it will suffer from `dos` attack.
The bug is in URL handling, which occurs if a URL contains two spaces. Too many requests can cause a dos attack.
Poc like:
```
a a a
GET 1.txt 1
```
contains two spaces

**Comment by ShiKangBao** [comment]
long request
```
GET 1.txt qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeGET 1.txt qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeGET 1.txt qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
```
will be twice response.
![image](https://user-images.githubusercontent.com/34313868/195310075-bcc24a06-b09a-41a3-bc8c-506e3b1eefee.png)

**Comment by landley** [comment]
It is not hardened against attack, no. It hasn't got a pool of child processes enforcing maximum simultaneous connections (that would be your inetd's problem). You can wrap it in timeout -i if you like?

You may have noticed a bunch of TODO entires in the code...

I've pondered writing a getline() variant with an input length limit, which glibc's getdelim() doesn't offer. I've mentioned before that this is an issue, although in certain contexts ala https://github.com/landley/toybox/blob/master/toys/posix/sed.c#L7 and https://github.com/landley/toybox/blob/master/toys/posix/sed.c#L479 I can't control what the input looks like and discarding data would corrupt the file. In this case there's probably a reasonable maximum bound on input size I could stop at (and just drop the connection). Of course w3c is <strike>useless</strike> silent. Microsoft's exploiter could handle 2083 characters (whether that's bytes or wide characters I dunno). Chrome can handle 2 megabyte URLs. Something called sitemaps dot org says 2k. Personally I'm thinking PATH_MAX... But "length of URL" and "length of cookie" are different things, and I haven't collected any data there or looked at other implementations. (Nor have I even started cgi support yet, but you'll notice the TODOs...)

> The bug is in URL handling, which occurs if a URL contains two spaces.

A URL can't contain two spaces, that's why the %20 escape exists. In http 1.1 the third space-separated field is the virtual server domain name (which we currently ignore). When the GET line has two spaces we insert a NUL terminator that strips off everything after the second space, thus truncating the URL before processing. The variable is then left pointing at the domain name if in case we want to add processing logic later, but right now it hasn't got any config for that.

How long does this input have to be to trigger the "repeat" thing you're seeing? Because I tried 10,000 bytes:

  $ python -c 'print "GET 1.txt %s\n" % ("@"*10000)' | ./httpd

And nothing seemed to misbehave? Are you sure it isn't an artifact of your terminal?
