### ISSUE TITLE
nc for ipv4/6 udp is listing but netstat not show this port opened

### ISSUE THREAD

**Issue by dxtr80** [landley/toybox#390]
I found a problem with Toybox 0.8.4 while trying to open UDP port with netcat. Netcat is showing that it is listening, but no UPD port is shown via netstat command.

No problem with TCP ipv4 and 6.

@landley is aware of this issue

**Comment by landley** [comment]
First bug report I had ever received via linkedin.

**Comment by landley** [comment]
Try commit 91fad2cdaa17

**Comment by landley** [comment]
Sigh, the test in my commit comment didn't have -u in it. Revisiting. (In theory "./netcat -u -s 127.0.0.1 -p 9876 -l" should talk to "./netcat -u 127.0.0.1 9876" so that's the test I'm trying to make work...)

**Comment by landley** [comment]
I have a patch here to make it work, but there's a problem: it doesn't know when the connection ends. You can use -W for a timeout, but otherwise you have to manually kill the server because "client exited" doesn't help, and connect() associates the port with a specific remote port. If you run another netcat to talk to the server, it gets a different port number so the second connection's refused.

I note that the one in Debian has a similar problem, "nc -u -l -p 9999" accepts exactly one connection and does not exit. "nc -u 127.0.0.1 9999" client works to talk to that, but if you exit and repeat it the others exit after the first message they send...

Is this what you expected? What's the usage pattern here?

(Making -L work accepting multiple incoming -u connections would be a bit of a can of worms on top of that problem...)

Rob

**Comment by landley** [comment]
Try commit 1cd2c07f94c3 but see caveats. Although it turns out other implementations are good for one connection (specific source port) and don't know when to close it either.

**Comment by landley** [comment]
In the absence of replies to the "try this commit", I'm assuming this was fixed.
