### ISSUE TITLE
Documentation site not readable comfortably on a cell phone

### ISSUE THREAD

**Issue by jidanni** [landley/toybox#397]
http://landley.net/toybox/ site requires the user to turn their cellphone into horizontal landscape mode, in order to barely be able thttp://landley.net/toybox/status.htmlo read the site. With a few simple changes the site could be mobile ready. Which makes sense, because the whole idea of toybox is to be used on cellphones. So users would be expected to be using a cellphone sooner or later to read the site! Thank you.

**Comment by landley** [comment]
I'm not a web designer, I hacked something together by hand in vi using tables. What changes do you want to make? (I'm not adding a stylesheet.)

**Comment by jidanni** [comment]
(From the point of a mobile only user:)
Let's see.
First that left sidebar "has to go".
As we see it wastes the left part of the screen all the way down.
![20221111T060154](https://user-images.githubusercontent.com/1230959/201336714-2a2271dd-cc1d-4504-beb3-de5c90561e7c.jpg)

**Comment by landley** [comment]
You: "requires", "barely be able", "with a few simple changes", "which makes sense" (not just to me but to everyone everywhere), "the whole idea is" (of the project, I.E. a thing you know better than the developers), "users would be expected" (again universally, not just by me) exclamation point.

Me: I'm not a web designer, what changes (to the html source) do want to make? (On a site where people post patches to projects' source.)

You: "This has to go", "you need to do!"... Issues orders and posts a screenshot of a nav bar taking up 15% of the horizontal space.

This is what you're "barely able to read"? No wait, you said you literally can't read that, but must go to landscape mode to barely be able to read it. The space wasted down the sides of kernel.org must render that completely illegible to you then. I blog about how eyestrain is my limiting factor for working (in as many words, ala https://landley.net/notes-2022.html#10-05-2022) but you should really see a doctor. And speaking of other sites, busybox.net has a nav bar quite like this. (It's where I got the idea, back in 2007.) https://www.linuxfromscratch.org/ has one too.

I'm all for improving things, but "I think this patch would be an improvement because X Y Z" is not the same as "let me explain your own project to you then order you to do work changing this 15 year old aesthetic issue because my personal taste is objective and absolute and I speak for all users everywhere".

Alternately, while viewing the page touch both thumbs to the screen and move them horizontally apart to zoom in. Then touch just one thumb to the screen and move it left, scrolling the screen to the right. This can put the nav bar off the left edge so you have just the text part on the screen.

**Comment by jidanni** [comment]
Okay. I'm back on a real cell phone today and here is  what we see:
![Screenshot_20221111-202840_Chrome Dev.jpg](https://user-images.githubusercontent.com/1230959/201452502-ebf214c6-b9e2-4155-aa2e-ddcde42d7c4c.jpg)
![Screenshot_20221111-202856_Chrome Dev.jpg](https://user-images.githubusercontent.com/1230959/201452513-52a7f63c-8ff0-47ad-983c-75cad9905737.jpg)

We are not able to take advantage of HTML automatically line breaking at the end of the screen.
