### ISSUE TITLE
Can't create temporary file on Android 12

### ISSUE THREAD

**Issue by jidanni** [landley/toybox#399]
On Android 12

> /sdcard/jidanni/bin/myscript[246]: can't create temporary file /data/local/sh8mcytt.tmp: Permission denied

And
> export TEMPDIR=...

didn't help.

Please be sure all the toybox commands don't try to use those directories that are out of bounds in Android 12, e.g., using non-rooted Samsung stock pre-installed toybox 8.4.

My shell script had some pipes and here-docs in it.

**Comment by landley** [comment]
You didn't say which command had the failure.

I can't find the string 'create temporary file' in the toybox or bionic sources except in bionic's versioner.cpp::compileHeaders() which seems unlikely to apply here? (And that starts "failed" insted of "can't"...)

Toysh isn't finished yet and current deployments of android are using mksh, which is probably what would be handling HERE documents in your script.

It's common practice to put the temporary file in the same directory as the destination file because then you can replace the original with an atomic rename(), which you can't do if the source and destination directories are on a different filesystem.

Since your script didn't do that, something told the code about "/data/local". Toybox doesn't contain the string "/data/local". AOSP's bionic has "/data/local/tmp" in its tempfile() crica 2012 and _PATH_TMP circa 2015, but not "/data/local" by itself. Dunno what samsung did, I haven't got its AOSP fork.

If "env" doesn't show a variable pointing to data/local, presumably one of your binaries has it hardwired in? (Try "strings"?)

**Comment by enh-google** [comment]
(note also that, if it wasn't a typo, `TEMPDIR` is a Windows thing; Unix uses `TMPDIR` without the `E`...)

**Comment by jidanni** [comment]
@enh-google bonanza! TMPDIR did it! Thanks!
(I hope somebody else fixes the problem someday.)
