### ISSUE TITLE
feature request: cttyhack

### ISSUE THREAD

**Issue by edubart** [landley/toybox#410]
I am giving a try to toybox, but I am missing something equivalent to [cttyhack](https://github.com/mirror/busybox/blob/master/shell/cttyhack.c) from busybox. My init scripts depends on this so the interactive terminal works correctly. Can toybox include something similar? It's very simple tool.

**Comment by landley** [comment]
http://lists.busybox.net/pipermail/busybox/2008-November/067722.html

Try oneit in busybox, like https://github.com/landley/toybox/blob/master/scripts/mkroot.sh#L134 does. (Although I suppose I should have it try to read /sys/class/tty/console/active internally rather than just expecting it on the command line.)

If you just want the console redirection but still to run your command as PID 1 (which blocks a bunch of signals, prevents it from calling the reboot() syscall, panics if it ever exits, etc), you could do it yourself in the shell, something like:

exec <>/dev/$(head -n 1 /sys/class/tty/console/active) 1>&0 2>&0

**Comment by edubart** [comment]
Thanks for the help, `oneit` did the work. So this is already builtin in toybox, closing.
