### ISSUE TITLE
stat -f -c %T /sys/fs/cgroup/memory display "unknown" instead of "cgroupfs"

### ISSUE THREAD

**Issue by chairwa** [landley/toybox#423]
mount -t tmpfs -o uid=0,gid=0,mode=0755 cgroup /sys/fs/cgroup
cd /sys/fs/cgroup
mkdir -p memory
mount -t cgroup -o memory cgroup memory

stat -f -c %T /sys/fs/cgroup/memory
unknown

Whereas on Linux, 
stat -f -c %T /sys/fs/cgroup/memory
cgroupfs

**Comment by enh-google** [comment]
apologies for not adding this when i last went through the list. i don't know if i mentioned this at the time, but basically i only added "real" the file systems from <linux/magic.h> and skipped cgroupfs/cgroup2fs/debugfs/tracefs etc.

rob: i'm guessing if we add one, we should add them all? let me know if you'd like a patch. that's nice easy friday afternoon "don't break anything before the weekend" work :-)

**Comment by landley** [comment]
I've been working on it all morning, I posted the above because I'm breaking for lunch. :)

**Comment by landley** [comment]
And all filesystems are "real" filesystems. There are four categories: block backed (ext2/vfat etc), server backed (nfs/cifs/v9fs/fuse etc), ram backed (ramfs/tmpfs), and synthetic (ala proc/sys). I even checked in some documentation on this: https://landley.net/toybox/doc/mount.html (Based on some random thing I posted to the busybox mailing list aeons ago, and then did a cleaned up version for livejournal, then...)

Cgroupfs is just a synthetic filesystem, like procfs and sysfs.

(There are also hybrid filesystems, the way devtmpfs is a synthetic filesystem that passes through to ram backed for newly created entries, and you could say "other filesystem backed" is a category ala unionfs and ecryptfs. Server backed is really "pipe backed" with data going across a serialized protocol, modulo NFSv2 sucking so much it uses udp instead of tcp and tries to parallelize it in a horrific way. But the four main filesystem categories are still useful to understand.)

**Comment by enh-google** [comment]
(yeah, s/"real"/block-backed/ in my earlier comment. sorry, i should have brought this up at the time and just added the lot...)

**Comment by landley** [comment]
Try commit 88ea9c97afa0

**Comment by landley** [comment]
Ping.

**Comment by enh-google** [comment]
("works for me" with the original submitter's example.)

**Comment by landley** [comment]
Calling it good. Open a new one if you've got another bug.
