### ISSUE TITLE
xargs needs "--" argument stopper

### ISSUE THREAD

**Issue by jidanni** [landley/toybox#425]
xargs needs the "--" argument stopper

```
$ adb shell which bu
/system/bin/bu
$ adb shell which bu \|xargs --help
Toybox 0.8.6-android multicall binary (see toybox --help)
usage: xargs [-0prt] [-snE STR] COMMAND...
$ adb shell which bu \|xargs -- --help
xargs: exec --help: No such file or directory
$ adb shell which bu | xargs -I{} adb shell {} --help #Ah, finally, using genuine GNU xargs.
#Yes, we could have just done this instead:
$ adb shell bu --help
```

**Comment by landley** [comment]
"Ah, finally, using genuine Gnu". Really? (To do _what_? It produced no output? Or did it say the second comment line you put there?) If you want to copy GPLv3 binaries onto your personal system, I'm happy to get out of the way of someone who thinks that BSD or MacOS or AIX binaries aren't "genuine" in their contexts.

You just _did_ use -- in xargs: "$ adb shell which bu \|xargs -- --help" returning "xargs: exec --help: No such file or directory" is saying it tried to exec --help as a command, because that's the first argument you gave it after you told it to stop parsing arguments with --. (It would also do that at the first unrecognized argument, but in that case the unrecognized argument wouldn't drop out and would be the executable it tried to run.)

I have no idea what you're trying to accomplish, other than to lobby for putting GPLv3 code onto the target. Which you don't need my help with on your own personal system?

**Comment by jidanni** [comment]
I am just trying to run "bu --help" without erasing anything I already wrote. Just adding things to the back.

**Comment by landley** [comment]
Toybox does have -- as is mentioned in "toybox --help", it's part of the standard argument parsing in lib/args.c, and thus in most commands?

'''
$ make clean defconfig toybox install_flat PREFIX=$PWD/here
...
$ here/toybox --help | grep '"--"'
The filename "-" means stdin/stdout, and "--" stops argument parsing.
$ here/toybox bu
toybox: Unknown command bu (see "toybox --help")
$ echo $'#!/bin/bash\ntoybox echo -- "$@"' > here/bu
$ chmod +x here/bu
$ echo $'one\ntwo\nthree' | PATH=$PWD/here xargs bu --help
--help one two three
'''

What am I missing here?

**Comment by landley** [comment]
I hate github wiki syntax, and the inability to easily disable it in comments.
