### ISSUE TITLE
Pathological patch can't be re-apply to original source without loose match

### ISSUE THREAD

**Issue by chriswailes** [landley/toybox#440]
Toybox fails to apply [the attached](https://github.com/landley/toybox/files/11872792/fails-to-re-apply.patch.gz) `git`-generated patch without the `-l` option.

This patch was generated from a modified version of [this source file](https://github.com/rust-lang/rust/blob/master/library/std/src/os/android/raw.rs)

**Comment by landley** [comment]
With debian's patch:

$ patch -p1 -i fails-to-re-apply.patch 
patching file library/std/src/os/android/raw.rs
Hunk #1 FAILED at 25.
Hunk #2 FAILED at 70.
Hunk #3 FAILED at 95.
Hunk #4 FAILED at 117.
Hunk #5 FAILED at 131.
Hunk #6 FAILED at 163.
Hunk #7 FAILED at 195.
7 out of 7 hunks FAILED -- saving rejects to file library/std/src/os/android/raw.rs.rej

**Comment by landley** [comment]
Yeah, debugging...

**Comment by landley** [comment]
Sorry, distracted by travel. I found the problem. but it's not a one line fix. The last hunk is the one failing, and the bug is that EOF detection is in the wrong place and moving it around involves some code restructuring. (The code got complicated adding fuzz support, it now has to back up and re-examine buffered lines because the proper start of the hunk may have been fuzzed past earlier, but EOF detection is still evaluated immediately instead of as part of the deferred re-examining.)

Working on it...

**Comment by landley** [comment]
Try commit 81611b019021

**Comment by landley** [comment]
Assuming this worked, poke me if you need more.
