### ISSUE TITLE
strings applet proposal

### ISSUE THREAD

**Issue by robang74** [landley/toybox#444]
Hi, you may be interested in this:

https://lists.busybox.net/pipermail/busybox/2023-July/090396.html

following the thread there are also performance tests under different usage conditions.

**Comment by landley** [comment]
It said it's gplv2? Toybox can't use gplv2 code.

The attachment's header says the old busybox version took 1.8 seconds to run on the busybox binary. With the debian preinstalled version (1.31 from 2019) I get:

$ time busybox strings $(which busybox) >/dev/null
real	0m0.016s
user	0m0.013s
sys	0m0.004s

What system are you running it on to get 1.8 seconds... Later in the thread you said a Core i5. Taking 1.8 seconds to run strings on a ~1 megabyte binary. Did it have to spin up a disk maybe?

I read down the thread with tito a bit and I don't understand the motivation for this rewrite? I very vaguely recall the binutils strings is parsing ELF sections rather than just searching for nul or newline terminated ascii in the binary, so the output being different isn't hugely surprising. (The brute force approach tends to produce false positives.) I was unaware of this tool being performance critical for anybody...?

**Comment by robang74** [comment]
Hi Rob, do not worry about the license because I am the author of the whole file and I can re-licensing it at my own will. I know that toybox is not under GPLv2. About strings, with Tito in the busybox m-list we concluded that there is no any need of another implementation of strings. I am closing this issue and thanks for your attention. Best regards, R-
