### ISSUE TITLE
Missing tls.h in released version 0.8.10 

### ISSUE THREAD

**Issue by kkarhan** [landley/toybox#451]
Apparently the tls.h is missing from the released version of toybox.

```
user@host:~/projects/os1337/build/toybox-0.8.10$ LDFLAGS=--static CROSS_COMPILE=i686-linux-musl-cross/bin/i686-linux-musl- make ARCH=x86 toybox
scripts/make.sh
generated/{flags.h}
Compile toybox
...........toys/net/wget.c:60:10: fatal error: tls.h: No such file or directory
   60 | #include <tls.h>
      |          ^~~~~~~
compilation terminated.
make: *** [Makefile:17: toybox] Error 1
```
![Bildschirmfoto vom 2023-08-28 04-15-32](https://github.com/landley/toybox/assets/30401796/5c0ed0df-bcbc-46f6-ab3f-90a48d3af726)

And yes, I really want a so radically cut-down toybox: that I did basically cut out anything from [.config](https://github.com/landley/toybox/files/12449589/config.txt) except the built-in wget...

Not shure if this issue only applies to [cross-compiling with musl for i686](https://landley.net/bin/toolchains/latest/i686-linux-musl-cross.tar.xz) as per [website](http://landley.net/toybox/index.html). 

But any help would be appreciated.
Thx.

**Comment by landley** [comment]
That's because tls.h isn't part of toybox, it's in /usr/include if you installed that host library. You can configure wget to use openssl, libtls, or neither (in which case it just supports http not https).

In the toybox source directory run "make menuconfig", and in the "networking commands" directory, note that wget has a sub-option "Enable HTTPS support for wget via LibTLS". The help text for that option says "Use TOYBOX_LIBCRYPTO to enable HTTPS support via OpenSSL." (Which is in the Toybox global settings menu. Yeah, it's awkward having them apart like that but OpenSSL if enabled is used for multiple things and libtls is only used here, so far.)

I have a todo item to implement built-in https support (something busybox has apparently done in the past few years), but that's post-1.0 release.

Either change your config not to request an external library, or install the library on your host to satisfy the build prerequisite you've configured in.

**Comment by landley** [comment]
Note that using this library while cross compiling means you need to install the library into your cross compiler, not into your host. You can use -I and -L to point it to where you built the library (-I is the include directory, -L is the library directory, yes both are capital letters), I did that with my own build of zlib in mkroot's optional dropbear build, see here:

https://github.com/landley/toybox/blob/master/mkroot/packages/dropbear#L29

(I only built the static libraries because I was doing a static build...)

**Comment by landley** [comment]
Looking at your project: the toybox shell is about 80% of the way to usable, but there are still some quite noticeable rough edges. (There's are reasons it's still in pending. Working on it...)

**Comment by kkarhan** [comment]
@landley thanks for your extensive replies and answers even if my question seems naive...

I [should've RTFM'd](https://github.com/landley/toybox/issues/451#issuecomment-1695295016) that before opening up an issue, tho [at the current stage](https://github.com/OS-1337/OS1337/blob/main/docu/project-goals.md#primary) of OS/1337 development.

Currently it should end up to be a [SSH terminal bootable from floppy](https://github.com/OS-1337/OS1337/blob/main/docu/project-goals.md#core-functionality).
Kinda like a frugal alternative to commercial solutions like [openthinclient's](https://openthinclient.com/en/) [thinclient-on-a-stick](https://wiki.openthinclient.org/display/OMD20201/openthinclient-on-a-Stick) that allows one to just boot and SSH into stuff... 

Wget with SSL is a "nice to have" at this point, and in subsequent versions [that ain't constrained by a 1440kB total size limit](https://github.com/OS-1337/OS1337/blob/main/docu/project-goals.md#secondary) I could workaround that and at worst shove a [tiny-curl](https://curl.se/tiny/) binary onto it.
Not elegant, I know, but a workaround that is feasible.

I mean, it would make things [easier in regards to some future tangents](https://github.com/OS-1337/spm) but I do already appreciate the fact that toybox seems to be a stable and simple way to avoid the whole mess of GNUtils and shared libraries, even tho that'll get me hated by so many purists aka RMS fanboys.

I just don't like BusyBox for the same reasons you do.

**Comment by kkarhan** [comment]
Feel free to close the issue - at least from my end that's fine...

I do hope this will at least help others stumbling upon the same issue to find out what the problem is and get hinted at pulling LibTLS or [OpenSSL](https://github.com/openssl/openssl) and installing it....

Thanks again for your time.

**Comment by kkarhan** [comment]
I would've used the [static precompiled binary provided](http://landley.net/toybox/bin/) if I wasn't [constrained by needing to fit it onto 1440kB](https://mstdn.social/@kkarhan/110965679190470398) disk space alongside the Kernel and Dropbear (as SSH-Client) [as of now](https://github.com/OS-1337/OS1337/blob/main/docu/project-goals.md#primary)...

OFC I do want to make things transparently reproducible so I [opensorced the .config for the quite gutted Toybox I build from source](https://github.com/OS-1337/OS1337/blob/main/build/0.CORE/build/toybox/0.8.10-i686.config)...

Besides that "SSH Terminal on a Bootable Floppy" version I do intend to use the published precompiled binaries as those can trade space for functionality very easily...

Thanks again for your time, but free to reopen the issue if need be.

**Comment by kkarhan** [comment]
Will keep [this issue referenced if need be](https://github.com/OS-1337/OS1337/issues/1)...
