### ISSUE TITLE
tar: --dereference does not work when --sort

### ISSUE THREAD

**Issue by jacky8hyf** [landley/toybox#456]
Repro steps:

```sh
mkdir /tmp/testing; cd /tmp/testing
touch foo
ln -sf foo bar
cd /tmp
tar cf testing.tar --dereference --sort -C /tmp/testing .
```

then
```sh
$ tar tvf testing.tar
drwxr-xr-x elsk/primarygroup         0  2023-09-29 12:03 ./
lrwxrwxrwx elsk/primarygroup         0  2023-09-29 12:03 ./bar -> foo
-rw-r--r-- elsk/primarygroup         0  2023-09-29 12:03 ./foo
```

If I drop `--sort`, then `--dereference` works correctly.

**Comment by jacky8hyf** [comment]
This could be worked around by providing `-T` or directly providing the list of files to archive, instead of using a directory (`.` in this case)

**Comment by landley** [comment]
I tried to reproduce this on the host debian one (to see what success looked like) and got "tar: invalid argument ‘-C’ for ‘--sort’, Valid arguments are:  - ‘none’  - ‘name’  - ‘inode’". I see I did (sort);: so the argument to sort is optional (takes it if cuddled ala -snone or --sort=none, but "-s sort" is two unrelated arguments...). The argument thing is kind of bonkers because "none" is what you get without the argument, "inode" is essentially random on modern filesystems, so only "name" makes any sense?

I used --sort=name and got:

$ tar tvf testing.tar
drwxr-xr-x landley/landley   0 2023-09-30 11:14 ./
-rw-r--r-- landley/landley   0 2023-09-30 11:13 ./bar
hrw-r--r-- landley/landley   0 2023-09-30 11:13 ./foo link to ./bar

Is that the output you expect here? First entry is type 5 (dir), second is 0 (file), third is 1 (hardlink).

Rob

**Comment by landley** [comment]
Ha, interesting corner case. I added the missing dereference flag, but it's still not treating entry 3 as a hardlink because the link count is 1, and I'm only adding entries with a link count >1 to the seen inode list because I didn't bother to do a fancy tree or hash table and instead used "most non-directory nodes have a link count of 1" as a filter to keep the linear search from getting punitive.

Probably the dirtree plumbing should record that the dirent saw a symlink but we read through it in the returned node somewhere, and then I can use that as a flag to add it to the potential hardlink list. Hmmm...

**Comment by landley** [comment]
Nope, doing that doesn't help. And the reason it doesn't is the second entry aliased with the first by following a symlink, but the first is a perfectly normal file (which already went past unremarked), and it has to record BOTH to see the collision. So with -h it has to record normal files with link count 1. Hmmm...

**Comment by landley** [comment]
Ok, try commit 658a944a6f77 and note that I didn't try to optimize the hardlink list; if performance obviously suffers doing tar -ch on giant directories I assume someone will let me know.

**Comment by jacky8hyf** [comment]
Thank you @landley ! Let us update our prebuilts and try out the new commit you have.

**Comment by enh-google** [comment]
> Thank you @landley ! Let us update our prebuilts and try out the new commit you have.

i'll take that as a request for new prebuilts... coming up!

**Comment by enh-google** [comment]
https://android-review.googlesource.com/c/platform/prebuilts/build-tools/+/2776234 has a toybox with everything up to and including yesterday's timeout fix.

**Comment by enh-google** [comment]
(currently blocked on a one-true-awk bug: https://github.com/onetrueawk/awk/issues/199)

**Comment by landley** [comment]
I plead the third.
