### ISSUE TITLE
find -cmin -amin -mmin

### ISSUE THREAD

**Issue by brian-leidos** [landley/toybox#58]
looks like this could easily be added to find, similar to ctime, atime, mtime, just changing the unit value to, what, 60?

**Comment by landley** [comment]
On 12/09/2016 12:38 PM, brian-leidos wrote:
> looks like this could easily be added to find, similar to ctime, atime,
> mtime, just changing the unit value to, what, 60?

Easily, sure. Please tell me more about your use case?

Explanation: I don't always know where to draw the line on featuritis so
for non-posix extensions I tend to wait for an actual user to show up
and complain about it being missing. "Package $NAME's makefile broke
because it did find -cmin" is a strong argument for adding it. "I was
reading through the man page and wondering why you hadn't done this, but
I've never used it before myself either" not so much. And yes, that
second one's come up more than once, which is why I ask. :)

Sigh, I should probably add that to the FAQ.

Thanks,

Rob

P.S. The shell's $((42*60)) is an underappreciated posix feature. Not a
substitute for other things people actually use, I'm just saying it's nice.

**Comment by brian-leidos** [comment]
My use case has to do with forensics. After I install or run an app, wanting to find what's changed in the file system. find -cmin/amin/mmin is supported in Linux, macOS, though I'm not sure about Posix. Obviously, I could put a file and use the -newer option, but as a forensic standpoint, I'd rather not be introducing new files like that. Make sense?

**Comment by landley** [comment]
On 12/11/2016 06:29 PM, brian-leidos wrote:
> My use case has to do with forensics. After I install or run an app,
> wanting to find what's changed in the file system. find -cmin/amin/mmin
> is supported in Linux, macOS, though I'm not sure about Posix.
> Obviously, I could put a file and use the -newer option, but as a
> forensic standpoint, I'd rather not be introducing new files like that.
> Make sense?

I.E. "this is an option I personally use". Got it.

Huh, digging into it, -atime isn't seconds, it's _days_. There should
probably be -asec and friends too, but I'm reluctant to add new API out
of the blue. (And if I was going to do that I'd want to add a suffix to
-atime to specify seconds, minutes, or hours.)

Ok, how about this: I'll implement the existing -amin/cmin/mmin api but
not add it to the help text, and _also_ implement an "-atime 3m" suffix
to specify units (years days hours minutes). Then _document_ the second
one, but accept both syntaxes for compatibility, and have "-atime" vs
"-amin" change which default units to use.

Sound reasonable?

Rob

**Comment by brian-leidos** [comment]
Hey Rob. Yeah, that sounds like an even better implementation. Thanks!

**Comment by enh** [comment]
these changes went in years ago (and don't seem to have caused any trouble), so close this bug?
