### ISSUE TITLE
need stty, tr, gawk to run inxi

### ISSUE THREAD

**Issue by amosbird** [landley/toybox#67]
Hi, this is a great toolbox. Thanks! However it still misses some tools for `inxi` to run. They are `stty`, `tr` and `gawk`.

**Comment by cb88** [comment]
All of those are already on the roadmap! http://landley.net/toybox/roadmap.html

BTW, you'll get more responsive replys from the mailing list than here.

**Comment by tpimh** [comment]
`tr` and `stty` are now in pending. Check if they have all the features that you need.

**Comment by sebma** [comment]
@cb88 I use `cut`, `grep`, `cut`, and `awk` filters in a script that I run at recovery (where `/usr` is not mounted).

In the meantime, I use busybox.

Approximately what month will the `awk` functionality be released in 2020 ?

**Comment by enh-google** [comment]
you might want to check out https://github.com/onetrueawk/awk for an awk you can use right now. that's what we're using on Android (both to _build_ Android and on the device itself).

**Comment by landley** [comment]
I'm currently focusing on getting the toybox shell finished, ala https://github.com/landley/toybox/commits/master/toys/pending/sh.c with behind the scenes stuff at https://landley.net/notes.html .

Right now I'm doing the can of worms that is the 7 types of argument expansion, and right at the _moment_ trying to get $((echo hello) | cat) to parse as subshell $( ( ) ) rather than arithmetic $(( )). (Ok, parse_word() already gets it right, but it leaves the resulting span as a quoted string for expand_arg_nobrace() to re-parse, and I'm trying not to duplicate the retroactive reclassification logic which would require lookahead here, so I probably need to get parse_word() to reach back and insert a space between those first two parentheses when the parenthetical count goes negative because (( wasn't accounted as normal parentheses, and yes $(((x+y)/3)) is math not subshell ($x and $y are automatically resolved) so you can't tell it's subshell until parsing reaches the _end_ of the span.

If somebody wants to write an awk the way Jarno Mäkipää is doing vi or Gavin Howard did bc, I'll happily stick it in pending. But as when _I_ plan to write one... dunno? Cleaning up and promoting existing toys/pending/*.c entries is higher priority than starting new ones at the moment. Closing tabs before opening more.

Elliott's external awk sounds like a reasonable stopgap until then.

**Comment by cesss** [comment]
Now that you talk about `awk` let me comment that "one true awk" doesn't support UTF-8, and that they don't plan to add support for it (I opened an issue for that, but their reply was that it was not in the roadmap and that it would imply a huge amount of work).

These days, with plenty of localized text files everywhere, I wouldn't consider an `awk` implementation ready for production use if it cannot process UTF-8 text.

**Comment by amakukha** [comment]
By the way, if somebody was to implement `awk` for toybox, what would be the desired feature set? @landley , @amosbird , @sebma 

These question arise:

1. Do we want it to be a drop-in replacement for `nawk` (a.k.a. "one-true-awk")?
2. Do we want it to use linear bytecode, like `mawk`? (Which is still six times faster than `gawk` for some simple workloads, e.g. [counting word frequency](https://codegolf.stackexchange.com/questions/188133/bentleys-coding-challenge-k-most-frequent-words).) 
3. Do we want to fully support Unicode on top of that? (Neither `nawk` nor `mawk` fully support it.)

I was thinking whether I could do "AWK for toybox" as my capstone university project. But I am afraid that if you want to keep it too simple, then it might look too easy for my project advisor and the judge panel… 

P.S. If not AWK, feel free to give me a suggestion whether I can otherwise spend two months of my time by contributing something meaningful to toybox and making my professors happy at same time.

**Comment by sebma** [comment]
@amosbird I don't need Unicode support in Linux rescue.
I don't want is linear bytecode.

**Comment by sebma** [comment]
@amakukha  I don't need Unicode support in Linux rescue.
I don't know what is linear bytecode.

**Comment by landley** [comment]
The toybox roadmap has awk because it's used in a lot of package build systems. Generally if you can build Linux From Scratch with this awk, it's probably good enough.

That said, toybox supports utf8 where possible, so if I was working on awk I'd support that. (I'm teaching toysh to understand unicode $IFS for example.)

I'm not personally familiar with the differences between nawk, mawk, and gawk.

**Comment by cesss** [comment]
@amakukha In my case, I'd need an awk that can process UTF-8 files with no issues (i.e: imagine you want to process a C/C++ source that has UTF-8 chars on it, which is supported by the C/C++ standards nowadays).

**Comment by enh-google** [comment]
stty, tr, and awk are all listed with their current state on https://landley.net/toybox/status.html with stty and tr being "partially implemented" and awk "not yet started".
