### ISSUE TITLE
Misleading help for sha1sum

### ISSUE THREAD

**Issue by Rikk** [landley/toybox#96]
Help for `sha1sum` says syntax is:
`usage: sha?sum [-b] [-c FILE] [FILE]...`
Which leads user to believe other sha commands would also be supported, for example, `sha512sum`. However, only `sha1sum` can be used in Toybox. Perhaps, it would be nice making it clear that other sha commands are not yet available here.

**Comment by landley** [comment]
On 06/29/2018 01:35 AM, Ricardo wrote:
> Help for |sha1sum| says syntax is:
> |usage: sha?sum [-b] [-c FILE] [FILE]...|
> Which leads user to believe other sha commands would also be supported, for
> example, |sha512sum|. However, only |sha1sum| can be used in Toybox. Perhaps, it
> would be nice making it clear that other sha commands are not yet available here.

They're available now if you enable ssl library support, and implementing local
versions is in the todo list (https://landley.net/toybox/status.html#todo) and
the roadmap (https://landley.net/toybox/roadmap.html).

Rob

**Comment by Rikk** [comment]
What are "local versions"?
Don't you have a bin with it enabled already? The ones in http://landley.net/toybox/downloads/binaries/ are disabled, right?

**Comment by landley** [comment]
On 06/29/2018 03:10 PM, Ricardo wrote:
> What are "local versions"?

A version implemented in toybox's C code rather than an external library, so it
can be a self-contained project providing all its own prerequisites and minimize
the circular dependencies at the start of hermetic build system bootstrapping.

As opposed to the external library callout ala:
https://github.com/landley/toybox/blob/master/toys/lsb/md5sum.c#L245
and
https://github.com/landley/toybox/blob/master/toys/lsb/md5sum.c#L340

> Don't you have a bin with it enabled already? The ones in
> http://landley.net/toybox/downloads/binaries/ are disabled, right?

The prebuilt binaries are defconfig, enabling all the completed built-in code.
They doesn't use the optional zlib or libssl callouts, if you want that you have
to enable those config symbols (in "make menuconfig" (under "toybox global
settings", Use libcrypto and Use libz).

Rob
